### ISSUE TITLE
Initial page load not correctly

### ISSUE THREAD

**Issue by hoangpham12345** [thoai-atb/mini-survey-system#1]
When first loaded, the "Login" in Nav will show "Not logged in".

**Comment by thoai-atb** [comment]
What do you mean? Can you show more details? If you have logged in, then after refreshing the page, then you're automatically logged in because it is stored in the cookie, that's why you don't see the "Not Logged In" message

**Comment by hoangpham12345** [comment]
The problem is when you just the page at first time, it tries to fetch user many times and keep displaying "Not logged in", then after 3 to 5 times, it shows "Login"
